### ISSUE TITLE
No progression on spark tab

### ISSUE THREAD

**Issue by Benvii** [OpenPathView/opv-status#11]
I don't have any progression on the spark tab, the response returned by the spark API is the following one : 

GET http://opv_master:4041/api/v1/applications
```
[ {
  "id" : "app-20180724202236-0000",
  "name" : "Make Campaign 'Jardins Juin 2018' (id: 1)",
  "attempts" : [ {
    "startTime" : "2018-07-24T18:22:34.050GMT",
    "endTime" : "1969-12-31T23:59:59.999GMT",
    "lastUpdated" : "2018-07-24T18:22:34.050GMT",
    "duration" : 0,
    "sparkUser" : "opv",
    "completed" : false,
    "endTimeEpoch" : -1,
    "startTimeEpoch" : 1532456554050,
    "lastUpdatedEpoch" : 1532456554050
  } ]
} ]
```

Is it a normal response ?

**Comment by zyioump** [comment]
The problem come from the spark server which don't allow cors, you must use an extension like cors everywhere to disable cors on your navigator. @Valdimus can you change spark configuration to allow cors ?
